version: '3.8'

services:
  # Database services

  # usersdb: PostgreSQL database for the Users API
  usersdb:
    container_name: usersdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usersDb
    restart: unless-stopped
    networks:
      - users-postgres-network
    ports:
      - "5432:5432"
    volumes:
      - ../postgresql-init:/docker-entrypoint-initdb.d

  # productsdb: MySQL database for the Products API
  productsdb:
    container_name: productsdb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productsDb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=admin
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - products-mysql-network
    volumes:
      - ../mysql-init:/docker-entrypoint-initdb.d
  
  # ordersdb: MongoDB database for the Orders API
  ordersdb:
    container_name: ordersdb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - orders-mongo-network
    volumes:
      - ../mongodb-init:/docker-entrypoint-initdb.d
  
  # distributedcache: Redis cache for the Orders API
  distributedcache:
    container_name: distributedcache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - services-network
  # API services

  # Users API service
  users.api:
    container_name: users.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=usersdb;Port=5432;Database=usersDb;User Id=postgres;Password=postgres;Include Error Detail=true;
    depends_on:
      - usersdb
    ports:
      - "7070:8080"
    networks:
      - users-postgres-network
      - services-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  # Products API service
  products.api:
    container_name: products.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=productsdb;Port=3306;Database=productsDb;User Id=appuser;Password=admin;
    depends_on:
      - productsdb
    ports:
      - "7071:8080"
    networks:
      - products-mysql-network
      - services-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # Orders API service
  orders.api:
    container_name: orders.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - USERS_MICROSERVICE_HOST=users.api
      - USERS_MICROSERVICE_PORT=8080
      - PRODUCTS_MICROSERVICE_HOST=products.api
      - PRODUCTS_MICROSERVICE_PORT=8080
      - ConnectionStrings__DefaultConnection=mongodb://ordersdb:27017
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - ordersdb
      - users.api
      - products.api
    ports:
      - "7072:8080"
    networks:
      - orders-mongo-network
      - services-network 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro