version: '3.8'

services:
  usersdb:
    image: postgres
    
  productsdb:
    image: mysql
  
  ordersdb:
    image: mongo

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Services/Users/Users.Api/Dockerfile

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.Api/Dockerfile

  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Services/Orders/Orders.Api/Dockerfile

volumes:
  postgres_users:
  mysql_products:
  mongodb_orders: