version: '3.8'

services:
  usersdb:
    image: postgres:latest
    
  productsdb:
    image: mysql:latest
  
  ordersdb:
    image: mongo:latest

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Services/Users/Users.Api/Dockerfile

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.Api/Dockerfile

  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Services/Orders/Orders.Api/Dockerfile
  
networks:
  orders-mongo-network:
    driver: bridge
  users-postgres-network:
    driver: bridge
  products-mysql-network:
    driver: bridge
  services-network:
    driver: bridge